rickstaa/stable-gym

CHANGELOG.md, CONTRIBUTING.md, README.md, package.json, setup.cfg, simzoo/version.py
- docs: fix contributing link
- chore(release): 0.5.17
=> fix contribution link

.github/workflows/test.yml
- chore(release): 0.6.10
- ci: fix release action
- chore(release): 0.6.11
- docs: change readme test badge
- chore(release): 0.6.12
- ci: fix test action python version bug
=> fix test action

package.json, pyproject.toml, tests/__snapshots__/test_oscillator.ambr, tests/test_oscillator.py
- chore(release): 0.6.13
- ci: don't run test on release
- chore(release): 0.6.14
- test: add oscillator env snapshot test
=> add oscillator test

.github/dependabot.yml, .github/workflows/stable_gym.yml, .github/workflows/test.yml, docs/source/conf.py, stable_gym/__init__.py, stable_gym/common/disturbances.py, stable_gym/common/disturber.py, stable_gym/common/utils.py, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator/oscillator_disturber.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost_disturber.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf_disturber.py
This pull request uses regex to add a punctuation mark to the docstrings to keep them consistent.
=> refactor: improve docstrings

docs/source/conf.py, docs/source/get_started/usage.rst, stable_gym/common/disturbances.py, stable_gym/common/disturber.py, stable_gym/common/utils.py, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator/oscillator_disturber.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost_disturber.py, stable_gym/envs/classic_control/ex3_ekf/__init__.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py
- docs: fix math
- refactor: improve docstrings
=> improve docstrings

examples/use_stable_gym_vectorized.py, setup.cfg, stable_gym/common/disturber.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost_disturber.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf_disturber.py, tests/test_cart_pole.py, tests/test_envs_register.py
=> refactor: import codebase

docs/source/dev/doc_dev.rst, docs/source/envs/biological/oscillator_complicated.rst, docs/source/envs/envs.rst, setup.cfg, stable_gym/__init__.py, stable_gym/common/disturber.py, stable_gym/envs/biological/__init__.py, stable_gym/envs/biological/oscillator/__init__.py, stable_gym/envs/biological/oscillator_complicated/README.md, stable_gym/envs/biological/oscillator_complicated/__init__.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated_disturber.py, stable_gym/envs/biological/oscillator_complicated/requirements.txt, stable_gym/envs/classic_control/__init__.py, stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/__init__.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost_disturber.py, stable_gym/envs/classic_control/ex3_ekf/__init__.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf_disturber.py, tests/__snapshots__/test_oscillator_complicated.ambr, tests/test_oscillator_complicated.py
This pull request adds the complicated oscillator environment from
[Han et al. 2020](https://arxiv.org/abs/2004.14288). This is a more challenging
version of the regular Oscillator environment with an additional protein, mRNA
transcription concentration and light input.
=> feat: add complicated oscillator environment

docs/source/envs/envs.rst, docs/source/envs/mujoco/walker2d_cost.rst, stable_gym/__init__.py, stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/mujoco/ant_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/hopper_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/walker2d_cost/README.md, stable_gym/envs/mujoco/walker2d_cost/__init__.py, stable_gym/envs/mujoco/walker2d_cost/requirements.txt, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py, tests/test_walker2d_cost.py
This pull request adds a modified version of the [Walker2d environment](https://gymnasium.farama.org/environments/mujoco/walker2d/) found in the [gymnasium](https://gymnasium.farama.org) package. In this modified version, the cost was replaced by a reward. This cost is the squared difference between Walker2d's forward velocity and a reference value (error).
=> feat: add 'Walker2dCost' environment

package-lock.json, package.json
This commit updates 'release-please' now that
https://github.com/googleapis/release-please/pull/1983 is merged.
=> chore: update 'release-please'

stable_gym/envs/mujoco/ant_cost/README.md, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/README.md, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/README.md, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py
This pull request adds a health penalty to certain Mujoco environments. This penalty is optional and can
be enabled using the 'include_health_penalty' environment argument.
=> feat: add mujoco envs health penalty

stable_gym/__init__.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/humanoid_cost/README.md, stable_gym/envs/mujoco/humanoid_cost/__init__.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/humanoid_cost/requirements.txt, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, tests/test_humanoid_cost.py
- feat: add 'HumanoidCost' environment
- test: add 'HumanoidCost' test
=> add humanoid cost env

docs/source/envs/envs.rst, docs/source/envs/mujoco/humanoid_cost.rst, stable_gym/__init__.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/humanoid_cost/README.md, stable_gym/envs/mujoco/humanoid_cost/__init__.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/humanoid_cost/requirements.txt, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, tests/test_humanoid_cost.py
- feat: add 'HumanoidCost' environment
- test: add 'HumanoidCost' test
- docs: add 'HumanoidCost' docs
=> add humanoid cost docs

docs/source/conf.py, docs/source/envs/envs.rst, docs/source/envs/robotics/fetch_reach_cost.rst, examples/use_stable_gym.py, examples/use_stable_gym_vectorized.py, package-lock.json, pyproject.toml, stable_gym/__init__.py, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py, stable_gym/envs/robotics/__init__.py, stable_gym/envs/robotics/fetch/README.md, stable_gym/envs/robotics/fetch/__init__.py, stable_gym/envs/robotics/fetch/fetch_reach_cost/README.md, stable_gym/envs/robotics/fetch/fetch_reach_cost/__init__.py, stable_gym/envs/robotics/fetch/fetch_reach_cost/fetch_reach_cost.py, stable_gym/envs/robotics/fetch/fetch_reach_cost/requirements.txt
This pull request adds a modified version of the
[FetchReach environment](https://robotics.farama.org/envs/fetch/reach/)
found in the [gymnasium robotics](https://robotics.farama.org) package.
In this modified
version, the cost was replaced by a reward. This cost is the Euclidean
distance between the achieved goal position and the desired goal:
=> feat: add 'FetchReachCost' environment

pyproject.toml
=> build: update gymnasium to v0.29.0

stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/minitaur_bullet_cost.py
This commit ensures that the doc comments won't cause flak8 errors and improves the codebase.
=> refactor: improve doc comments

tests/__snapshots__/test_cartpole_cost.ambr, tests/__snapshots__/test_fetch_reach_cost.ambr, tests/test_ant_cost.py, tests/test_cartpole_cost.py, tests/test_cartpole_tracking_cost.py, tests/test_fetch_reach_cost.py, tests/test_half_cheetah_cost.py, tests/test_hopper_cost.py, tests/test_humanoid_cost.py, tests/test_minitaur_cost.py, tests/test_oscillator.py, tests/test_oscillator_complicated.py, tests/test_swimmer_cost.py, tests/test_walker2d_cost.py
This pull request improves the tests by replacing the metaclass initialization steps with [fixtures](https://docs.pytest.org/en/6.2.x/fixture.html).
=> test: improve tests with fixtures

.github/workflows/stable_gym.yml, .github/workflows/test.yml, CONTRIBUTING.md, docs/source/envs/envs.rst, docs/source/envs/robotics/quadx_hover_cost.rst, docs/source/envs/robotics/quadx_tracking_cost.rst, docs/source/envs/robotics/quadx_waypoints_cost.rst, pyproject.toml, stable_gym/envs/robotics/__init__.py, tests/test_envs_register.py, tests/test_quadx_hover_cost.py, tests/test_quadx_tracking_cost.py, tests/test_quadx_waypoints_cost.py
This pull request handles the RuntimeError error that is thrown by PyFlyt when PyBullet is not build with numpy support. See https://github.comhoots/PyFlyt/pull/8 for more information.
=> test: fix PyFlyt runtime error

.github/workflows/stable_gym.yml, .github/workflows/test.yml, pyproject.toml, stable_gym/common/utils.py, tests/test_quadx_hover_cost.py, tests/test_quadx_tracking_cost.py, tests/test_quadx_waypoints_cost.py
This pull request adds a temporary fix to ensure the Quadrotor tests run (see https://github.com/jjshoots/PyFlyt/pull/9).
=> fix: add tempory PyFlyt RuntimeWarning fix

stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py
This pull request improves the code of the biological environments.
=> refactor(biological): improve code syntax

docs/source/dev/doc_dev.rst, docs/source/envs/envs.rst, docs/source/get_started/install.rst
This commits adds tests for the LATC algorithm.
=> test(latc): add LATC tests

stable_gym/common/utils.py, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py, stable_gym/envs/robotics/fetch/fetch_reach_cost/fetch_reach_cost.py, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/minitaur_bullet_cost.py, stable_gym/envs/robotics/quadrotor/quadx_hover_cost/quadx_hover_cost.py, stable_gym/envs/robotics/quadrotor/quadx_tracking_cost/quadx_tracking_cost.py, stable_gym/envs/robotics/quadrotor/quadx_waypoints_cost/quadx_waypoints_cost.py
This pull request adds the 'action_space_dtype' and 'observation_space_dtype' to all environments so users can set the action and observation space dtypes.
=> feat: add environment observation and action dtype arg

examples/requirements.txt, pyproject.toml, stable_gym/envs/biological/oscillator/requirements.txt, stable_gym/envs/biological/oscillator_complicated/requirements.txt, stable_gym/envs/classic_control/cartpole_cost/requirements.txt, stable_gym/envs/classic_control/cartpole_tracking_cost/requirements.txt, stable_gym/envs/classic_control/ex3_ekf/requirements.txt, stable_gym/envs/mujoco/ant_cost/requirements.txt, stable_gym/envs/mujoco/half_cheetah_cost/requirements.txt, stable_gym/envs/mujoco/hopper_cost/requirements.txt, stable_gym/envs/mujoco/humanoid_cost/requirements.txt, stable_gym/envs/mujoco/swimmer_cost/requirements.txt, stable_gym/envs/mujoco/walker2d_cost/requirements.txt
This pull request updates gymnasium to [v0.29.1](https://github.com/Farama-Foundation/Gymnasium/releases/tag/v0.29.1).
=> chore: update gymnasium to v0.29.1

README.md, stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/biological/oscillator_complicated/README.md, stable_gym/envs/robotics/fetch/fetch_reach_cost/README.md
- docs: fix documentation urls
- docs: improve docs
=> improve docs

.alexrc, docs/source/conf.py, stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/README.md, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py, tests/__snapshots__/test_cartpole_cost.ambr, tests/__snapshots__/test_cartpole_tracking_cost.ambr
This pull request ensures the random initialization of the card position is done in the `[-5,5]` range used in Han's paper. It also improves the CartPoleCost and CartPoleTrackingCost environment documentation to clearly state what was changed compared to the commonly used Gymnasium CartPole environment.
=> docs: improve cartpole documentation

stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/README.md, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/minitaur_bullet_cost.py
This pull request fixes several minor errors in the docs and docstrings. It also improves the CartPoleCost documentation.
=> docs: improve docs and docstrings

stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/README.md, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py
This pull request fixes some minor typos.
=> docs: fix minor docs typos
