rickstaa/stable-gym

docs/source/conf.py, docs/source/envs/envs.rst, docs/source/envs/mujoco/swimmer_cost.rst, examples/use_stable_gym.py, pyproject.toml, stable_gym/__init__.py, stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/classic_control/__init__.py, stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, stable_gym/envs/classic_control/ex3_ekf/requirements.txt, stable_gym/envs/mujoco/__init__.py, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/__init__.py, stable_gym/envs/mujoco/swimmer_cost/requirements.txt, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, tests/test_cart_pole.py, tests/test_swimmer_cost.py
This pull request adds the SwimmerCost environment. This environment was based on the [swimmer environment](https://gymnasium.farama.org/environments/mujoco/swimmer/) of the [gymnasium library](https://gymnasium.farama.org). Compared to that environment, only the reward was changed so that a reference speed was tracked.
=> feat: add SwimmerCost environment

stable_gym/__init__.py, stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/__init__.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/requirements.txt, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/__init__.py, tests/test_half_cheetah_cost.py
This pull request adds a modified version of the [HalfCeetah environment](https://gymnasium.farama.org/environments/mujoco/half_cheetah/) found in the [gymnasium](https://gymnasium.farama.org) package. In this modified version, the cost was replaced by a reward. This cost is the squared difference between HalfCheetah's forward velocity and a reference value (error).
=> feat: add 'HalfCheetahCost' environment

stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/README.md, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/mujoco/ant_cost/README.md, stable_gym/envs/mujoco/ant_cost/__init__.py, stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/__init__.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/README.md, stable_gym/envs/mujoco/hopper_cost/__init__.py, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/humanoid_cost/README.md, stable_gym/envs/mujoco/humanoid_cost/__init__.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/__init__.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/README.md, stable_gym/envs/mujoco/walker2d_cost/__init__.py, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py
This pull request adds the ability to randomize the velocity reference in the
Mujoco environment. It also adds the `exclude_reference_from_observation`
argument which can be used to remove the reference from the observation.
=> feat: add velocity randomize and exclude reference arguments

stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/ex3_ekf/ex3_ekf.py, tests/__snapshots__/test_cart_pole.ambr, tests/__snapshots__/test_oscillator.ambr, tests/__snapshots__/test_oscillator_complicated.ambr, tests/test_cart_pole.py, tests/test_oscillator.py, tests/test_oscillator_complicated.py
This pull request ensures the `cost_range` is renamed to `reward_range`. This is done since this is the
variable used in the Gymnasium package. Additionally, the observation/action and reward space
accuracy was increased to float64.
=> feat: fix 'reward_range' name and space accuracy

pyproject.toml, stable_gym/__init__.py, stable_gym/common/utils.py, stable_gym/envs/mujoco/ant_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/robotics/__init__.py, stable_gym/envs/robotics/minitaur_cost/README.md, stable_gym/envs/robotics/minitaur_cost/__init__.py, stable_gym/envs/robotics/minitaur_cost/minitaur_cost.py, stable_gym/envs/robotics/minitaur_cost/requirements.txt, tests/__snapshots__/test_minitaur_cost.ambr, tests/test_minitaur_cost.py
This pull request adds a modified version of the [Minitaur environment](https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_data/quadruped) found in the [bullet3 package](https://pybullet.org/wordpress/) package. In this modified version, the objective was changed to a velocity-tracking task. To do this, the reward is replaced with a cost. This cost is the squared difference between the Minitaur's forward velocity and a reference value (error).
=> feat: add 'MinitaurCost' environment

tests/test_ant_cost.py, tests/test_fetch_reach_cost.py, tests/test_half_cheetah_cost.py, tests/test_hopper_cost.py, tests/test_humanoid_cost.py, tests/test_minitaur_cost.py, tests/test_swimmer_cost.py, tests/test_walker2d_cost.py
This pull request disables the snapshot tests during CI since snapshots are not always deterministic over different python versions and systems.
=> disable snapshot tests in CI

stable_gym/common/utils.py, tests/__snapshots__/test_ant_cost.ambr, tests/__snapshots__/test_fetch_reach_cost.ambr, tests/__snapshots__/test_half_cheetah_cost.ambr, tests/__snapshots__/test_hopper_cost.ambr, tests/__snapshots__/test_humanoid_cost.ambr, tests/__snapshots__/test_minitaur_cost.ambr, tests/__snapshots__/test_swimmer_cost.ambr, tests/__snapshots__/test_walker2d_cost.ambr, tests/test_ant_cost.py, tests/test_fetch_reach_cost.py, tests/test_half_cheetah_cost.py, tests/test_hopper_cost.py, tests/test_humanoid_cost.py, tests/test_minitaur_cost.py, tests/test_swimmer_cost.py, tests/test_walker2d_cost.py
This pull request decreases the snapshot test precision to prevent tests from failing due to small numerical differences caused by hardware or library differences.
=> test: decrease the snapshot test precision

stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py
This commit ensures that the right periodic formula is used. In the old formula the period was used
instead of the expected frequency.
=> fix: fix oscillator reference formula

stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/README.md, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py
This pull request removes the 'reference_type' argument since the same can already be achieved by setting the 'reference_frequency' to `0`.
=> feat(oscillator): simplify oscillator environments

stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/biological/oscillator/oscillator.py, stable_gym/envs/biological/oscillator_complicated/README.md, stable_gym/envs/biological/oscillator_complicated/oscillator_complicated.py, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/README.md, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py
This pull request ensures the right frequency is used in the environments, and a warning is only thrown
about excluding the reference and reference error when the reference signal is not constant.
=> refactor(biological/classical): fix small inconsistencies

stable_gym/envs/robotics/quadrotor/quadx_tracking_cost/README.md, stable_gym/envs/robotics/quadrotor/quadx_tracking_cost/__init__.py, stable_gym/envs/robotics/quadrotor/quadx_tracking_cost/quadx_tracking_cost.py, tests/__snapshots__/test_quadx_tracking_cost.ambr
This commit adds the `reference`, `state_of_interest` and `reference_error` keys to the step info
dictionary.
=> feat(quadxtrackingcost): add extra keys to environment step info dictionary

.github/workflows/documentation.yml, .github/workflows/stable_gym.yml, .github/workflows/test.yml, CONTRIBUTING.md, docs/source/envs/envs.rst, docs/source/envs/robotics/quadx_hover_cost.rst, docs/source/envs/robotics/quadx_tracking_cost.rst, docs/source/envs/robotics/quadx_waypoints_cost.rst, stable_gym/envs/robotics/__init__.py
This removes the Numpy warning on PyFlyt. I've fixed it on PyFlyt's end to still function without Numpy.
Given that the environments within Stable Gym do not use the camera components, building PyBullet with Numpy is probably not mission critical, so a warning stating so is maybe not necessary?
Lmk if you would prefer to have that warning.
=> Remove requirement for Numpy on PyFlyt

stable_gym/envs/robotics/quadrotor/quadx_waypoints_cost/README.md, stable_gym/envs/robotics/quadrotor/quadx_waypoints_cost/quadx_waypoints_cost.py, tests/__snapshots__/test_quadx_waypoints_cost.ambr
This pull request fixes a bug when calculating the directional penalty. It also adds the `reference`, `state_of_interest` and `reference_error` to the info returned by the environment step and reset methods.
=> fix(quadxwaypointscost): fix directional penalty and add extra step info keys

stable_gym/envs/robotics/quadrotor/quadx_hover_cost/README.md, stable_gym/envs/robotics/quadrotor/quadx_hover_cost/quadx_hover_cost.py, tests/__snapshots__/test_quadx_hover_cost.ambr
This pull request adds the `reference`, `state_of_interest` and `reference_error` keys to the info dictionary that is returned by the environment step and reset methods.
=> feat(quadxhover): add extra information to step/reset info

stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py
This pull request adds the `reference`, `state_of_interest` and `reference_error` keys to the info dictionary that is returned by the step and reset methods.
=> feat(classicalcontrol): add additional info to step/reset return

stable_gym/envs/mujoco/ant_cost/ant_cost.py, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py, stable_gym/envs/mujoco/hopper_cost/hopper_cost.py, stable_gym/envs/mujoco/humanoid_cost/humanoid_cost.py, stable_gym/envs/mujoco/swimmer_cost/swimmer_cost.py, stable_gym/envs/mujoco/walker2d_cost/walker2d_cost.py
This pull request adds the `reference`, `state_of_interest` and `reference_error` keys to the info dictionary that is returned by the environment step and reset methods.
=> feat: add reference info to step/reset return

stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/minitaur_bullet_cost.py, tests/__snapshots__/test_minitaur_cost.ambr
This pull request adds the `reference`, `state_of_interest` and `reference_error` to the info dictionary that is returned by the environment's step and reset methods.
=> feat(minitaur): add minitaur step/reset reference info return

stable_gym/envs/robotics/fetch/fetch_reach_cost/README.md, stable_gym/envs/robotics/fetch/fetch_reach_cost/fetch_reach_cost.py, tests/__snapshots__/test_fetch_reach_cost.ambr
This commit adds the `reference`, `state_of_interest` and `reference_error` to the dictionary that
is returned by the step/reset methods of the FetchReachCost environment.
=> feat(fetchreachcost): add reference info to step/reset return

stable_gym/envs/biological/oscillator/README.md, stable_gym/envs/mujoco/ant_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/hopper_cost/README.md, stable_gym/envs/mujoco/humanoid_cost/README.md, stable_gym/envs/mujoco/swimmer_cost/README.md, stable_gym/envs/mujoco/walker2d_cost/README.md, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/README.md
This pull request adds some missing step return keys to the environment docs (i.e. `reference`,
`state_of_interest` and `reference_error`).
=> docs: add missing step return info dict keys

tests/test_envs_register.py, tests/test_quadx_hover_cost.py, tests/test_quadx_tracking_cost.py, tests/test_quadx_waypoints_cost.py
This pull request removes the added hotfixes because PyFlyt caused errors when Pybullet was not installed with Numpy support. These issues have been fixed on the upstream (see https://github.com/jjshoots/PyFlyt/commit/6aad763d2da618d82b78c841116c9274ae2a13ba).
=> remove pyflyt bullet numpy fixes

tests/__snapshots__/test_quadx_hover_cost.ambr, tests/__snapshots__/test_quadx_tracking_cost.ambr, tests/__snapshots__/test_quadx_waypoints_cost.ambr, tests/test_quadx_hover_cost.py, tests/test_quadx_tracking_cost.py, tests/test_quadx_waypoints_cost.py
This pull request decreases the snapshot test precision of the QuadCopter environments. This was done since they are not deterministic when running on different hardware (e.g. GitHub servers).
=> test: decrease quadx snapshot precision

CONTRIBUTING.md, docs/source/dev/add_new_envs.rst, package-lock.json, pyproject.toml, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/README.md, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/__init__.py, stable_gym/envs/robotics/minitaur/minitaur_bullet_cost/minitaur_bullet_cost.py
This pull request fixes several documentation urls and improves some documentation syntax.
=> docs: fix documentation urls

docs/source/conf.py, docs/source/envs/envs.rst, docs/source/index.rst
This commit adds a comment that lets people know that they have to set
the ``positive_reward`` argument to ``True`` if they want to use the
environments in the
[ros-gazebo-gym](https://github.com/rickstaa/ros-gazebo-gym) package
with the stable RL agents in the
[stable-learning-control](https://github.com/rickstaa/stable-learning-control)
package.
=> docs: add ros-gazebo-gym positive reward comment

stable_gym/envs/classic_control/cartpole_cost/README.md, stable_gym/envs/classic_control/cartpole_cost/cartpole_cost.py, stable_gym/envs/classic_control/cartpole_tracking_cost/README.md, stable_gym/envs/classic_control/cartpole_tracking_cost/cartpole_tracking_cost.py
This pull request ensures that the CartPole(Tracking)Cost reward range scales with the `max_cost` environment output.
=> fix(cartPole): ensure reward range scales with max cost

stable_gym/envs/mujoco/half_cheetah_cost/README.md, stable_gym/envs/mujoco/half_cheetah_cost/half_cheetah_cost.py
This pull request adds a small comment to the HalfCheetahCost environment that explains how our version differs from [Han et al. 2020's](https://github.com/hithmh/Actor-critic-with-stability-guarantee/blob/8a90574fae550e98a9b628bbead6da7f91a51fff/ENV/env/mujoco/half_cheetah_cost.py#L23) codebase.
=> docs(halfCheetahCost): add Han et al. 2020 codebase difference comment
